version: '3.9'

services:

  api.gateway.webapi:
    ports:
      - 5060:5060
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro

  api.admin.webapi:
    ports:
      - 5061:5061
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      # - ASPNETCORE_ENVIRONMENT=Test
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro

  api.basket.webapi:
    ports:
      - 5062:5062
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      # - ASPNETCORE_ENVIRONMENT=Test
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro

  api.catalog.webapi:
    ports:
      - 5063:5063
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      # - ASPNETCORE_ENVIRONMENT=Test
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro

  api.employee.webapi:
    ports:
      - 5064:5064
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      # - ASPNETCORE_ENVIRONMENT=Test
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro

  api.identity.webapi:
    ports:
      - 5065:5065
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      # - ASPNETCORE_ENVIRONMENT=Test
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro

  api.ordering.webapi:
    ports:
      - 5066:5066
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      # - ASPNETCORE_ENVIRONMENT=Test
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro

  api.payment.webapi:
    ports:
      - 5067:5067
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      # - ASPNETCORE_ENVIRONMENT=Test
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro

  api.register.webapi:
    ports:
      - 5068:5068
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      # - ASPNETCORE_ENVIRONMENT=Test
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro

  api.webhooks.webapi:
    ports:
      - 5069:5069
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      # - ASPNETCORE_ENVIRONMENT=Test
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
  
  # api.admin.tests:
  #   image: ${DOCKER_REGISTRY-}api.admin.tests
  #   container_name: api.admin.tests
  #   restart: always
  #   build:
  #     context: .
  #     dockerfile: backend/API.Admin.Tests/Dockerfile
  #   depends_on:
  #     - api.admin.webapi
  #     - sqlserver
  #     - mongoserver
  #     - kafka
  #     - rabbitmq
  #     - redis
  #   networks:
  #     - app-backend
  #   entrypoint: ["dotnet", "test", "API.Admin.Tests.dll", "--logger:trx"]

