#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER app
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["backend/API.Basket/API.Basket.csproj", "backend/API.Basket/"]
COPY ["backend/BuildingBlocks/Domain/Domain.Basket/Domain.Basket.csproj", "backend/BuildingBlocks/Domain/Domain.Basket/"]
RUN dotnet restore "./backend/API.Basket/API.Basket.csproj"
COPY . .
WORKDIR "/src/backend/API.Basket"
RUN dotnet build "./API.Basket.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./API.Basket.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "API.Basket.dll"]